case1:
	python3 main.py < cases/1.txt > answers/1.txt
	diff answers/1.txt truths/1.txt

case2:
	python3 main.py < cases/2.txt > answers/2.txt
	diff answers/2.txt truths/2.txt

case3:
	python3 main.py < cases/3.txt > answers/3.txt
	diff answers/3.txt truths/3.txt

case4:
	python3 main.py < cases/4.txt > answers/4.txt
	diff answers/4.txt truths/4.txt
